# Generated by Django 4.2.11 on 2024-03-26 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_file_course_alter_file_original_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="number",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=20, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
