# Generated by Django 4.2.11 on 2024-04-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_file_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="peeruser",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
