# Generated by Django 4.2.11 on 2024-04-12 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_file_points_peeruser_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="points",
        ),
        migrations.AddField(
            model_name="file",
            name="downvotes",
            field=models.ManyToManyField(
                related_name="downvoted_file", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="upvotes",
            field=models.ManyToManyField(
                related_name="upvoted_file", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
