# Generated by Django 4.2.11 on 2024-04-21 04:01

from django.db import migrations
import os

import json


def load_data_from_json(apps, schema_editor):
    Professor = apps.get_model("api", "Professor")
    json_file = os.path.abspath(
        os.path.join(
            os.path.dirname(__file__), "..", "utils", "JSON_inputs", "faculty_list.json"
        )
    )

    with open(json_file, "r") as f:
        data = json.load(f)

    for item in data:
        try:
            Professor.objects.create(
                name=item["name"],
            )
        except Exception as e:
            print("Error:", str(e))


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_add_course_data"),
    ]

    operations = [
        migrations.RunPython(load_data_from_json),
    ]
